# modern netlify.toml
[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "http://lab.ezyy.cloud:8082/api/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/api/socket/*"
  to = "ws://lab.ezyy.cloud:8082/api/:splat"
  status = 200
  force = true